# Generated by Django 4.2.11 on 2024-05-17 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_team_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
